/** Auto-generated by scripts/generate-gbcharities-from-tgb.js
 *  Source: https://public-api.sandbox.thegivingblock.com/v1/organizations/list
 *  Generated: 2025-11-12T16:35:38.141Z
 *
 *  Note: this file is safe to commit; tokens must NOT be committed.
 */

export type Charity = {
  id: string;
  name: string;
  logoUrl?: string;
  website?: string;
  blurb?: string;
  uuid?: string | null;
  country?: string | null;
};

export const CHARITIES: Charity[] = [
  {
    "id": "1189132061",
    "name": "Uncommon Giving Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/50b16f83-51ee-48d1-b608-96a245c34f22.jpeg",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "8b587732-6d40-484f-a0c8-722e5fe0a52a",
    "country": "USA"
  },
  {
    "id": "1189132058",
    "name": "OnboardOrg In Sandbox",
    "logoUrl": "",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "7c53ffaa-a92d-44c3-b2c1-a0c3abb0f838",
    "country": "USA"
  },
  {
    "id": "1189132052",
    "name": "Alveus Sanctuary Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/2ff2419a-77f1-4fdd-b765-767a02e70dd1.png",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "4d606c7e-7085-4119-9e06-d442aa475082",
    "country": "USA"
  },
  {
    "id": "1189132045",
    "name": "CSU Long Beach (Sandbox)",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/cabaaa2c-86f3-4f87-b74b-4a09820b26c2.jpg",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "16faa2e5-ec77-4021-afc5-1f821189cfd1",
    "country": "USA"
  },
  {
    "id": "1189132038",
    "name": "World Child Cancer Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/72dee9d6-1624-4421-8606-a3c53f8db496.jpeg",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "b9f76d7f-7116-445e-bf4c-2c4d7c093f25",
    "country": "USA"
  },
  {
    "id": "1189132037",
    "name": "GoFundMe Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/76ee026c-94be-4284-8554-09c318f69ca5.jpg",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "5707d27f-390e-4f2f-9150-92bbdc6b4787",
    "country": "USA"
  },
  {
    "id": "1189132029",
    "name": "Young Americans for Liberty Foundation Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/1b900bc1-c0a9-4bbf-b8a9-2f599bae2468.jpg",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "628702c1-749a-41fa-9600-c39fb01335b7",
    "country": "USA"
  },
  {
    "id": "1189132028",
    "name": "goDonate Sandbox - GBP",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/4c53aef1-351d-49a6-b559-1c41f9c2f5e5.jpeg",
    "website": "",
    "blurb": "Country: GBR",
    "uuid": "7fe7703c-235c-48e5-be57-01a683543a7b",
    "country": "GBR"
  },
  {
    "id": "1189132027",
    "name": "ALS Network - Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/14a9059d-8115-4b10-8540-b13ce098dc22.png",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "7d81150d-2f35-42ab-8a7e-de008f9aaefb",
    "country": "USA"
  },
  {
    "id": "1189132024",
    "name": "Charity On Top Sandbox",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/734fb1e0-9844-48f5-ac88-573881e1dc83.png",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "5a6fc558-24da-4984-9d26-8346a674efe1",
    "country": "USA"
  },
  {
    "id": "1189132020",
    "name": "The Giving Block Demo",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/3e65cdc7-5d68-4784-a841-23d967b899cc.png",
    "website": "",
    "blurb": "Country: USA",
    "uuid": "e7561233-6794-423f-a7a5-29a7e9be1c5b",
    "country": "USA"
  },
  {
    "id": "1189132019",
    "name": "Schwab Charitable - DAF Giving 360",
    "logoUrl": "https://static.sandbox.thegivingblock.com/organization_logo/c824f419-43a4-4ee5-8f37-96d10f0b9d4b.png",
    "website": "",
    "blurb": "",
    "uuid": "f29fd1e1-5443-45c1-a1b2-08c14c1efada",
    "country": ""
  }
];

export const getCharityById = (id?: string | null) =>
  CHARITIES.find(c => c.id === id);

export const getOrgIdByName = (name?: string | null) => {
  if (!name) return undefined;
  const norm = name.trim().toLowerCase();
  return CHARITIES.find(c => c.name.trim().toLowerCase() === norm)?.id;
};

export const searchCharities = (query: string, limit = 10) => {
  const q = query.trim().toLowerCase();
  if (!q) return CHARITIES.slice(0, limit);
  return CHARITIES.filter(c => c.name.toLowerCase().includes(q)).slice(0, limit);
};
