import type { TemplateContent } from './types';

const relatedGames = [
  { label: 'All event formats', to: '/event-formats' },
  { label: 'Quiz fundraisers', to: '/event-formats/quiz' },
  { label: 'Book a demo',to: '/contact' },
];

export const gamePages: Record<string, TemplateContent> = {
  quiz: {
    path: '/event-formats/quiz', seoTitle: 'Quiz Fundraisers', seoDescription: 'Run quiz fundraisers with ticketing, player records, payment tracking and reports for committees.', eyebrow: 'Event format', h1: 'Quiz fundraisers made easier to run', intro: 'A familiar fundraising format supported by clearer setup, ticketing, player management, payment tracking and reports.', primaryCta: { label: 'Book a demo',to: '/contact' }, secondaryCta: { label: 'Explore event formats', to: '/event-formats' }, imageKey: 'communityQuizNight', status: 'live', visualEmphasis: 'video_heavy',
    videoSlot: { title: 'Add a short quiz demo video here', text: 'The quiz page should be video and screenshot heavy because visitors need to see both the host flow and the player experience.', imageKey: 'quizGameplayScreenshot', videoLabel: 'Quiz gameplay demo placeholder', transcript: 'Show the organiser setup, supporter ticket page, player screen, host controls and final report in a short practical walkthrough.' }, statusLabel: 'Available first',
    problemTitle: 'Quiz nights work, but the admin can be heavy', problemText: 'Organisers need to promote the event, collect entries, manage teams or players, track payments and report back afterwards.', solutionTitle: 'A quiz fundraiser flow designed for real organisers', solutionText: 'FundRaisely gives the quiz its own structure, from setup and ticketing through to gameplay support and reports.',
    benefits: [ { title: 'Supporters know what to do', text: 'Use a clear ticket and joining journey before the event.' }, { title: 'Hosts stay organised', text: 'Keep players, payments and event details together.' }, { title: 'Works in-person or remote', text: 'Use the quiz as part of a live event or a more flexible digital fundraiser.' }, { title: 'Reports after the event', text: 'Review totals, prizes and participation once the quiz is complete.' } ],
    process: [ { title: 'Create the quiz fundraiser', text: 'Set the event details, entry fee, prizes and any fundraiser options.' }, { title: 'Share the link', text: 'Invite supporters to buy or reserve their place.' }, { title: 'Run the quiz', text: 'Host the game with a structured player and question flow.' }, { title: 'Review the report', text: 'Check participation, payment status and event totals afterwards.' } ],
    screenshotSlots: [ { title: 'Quiz setup', description: 'Add a screenshot of the setup wizard or organiser flow.', imageKey: 'dashboardScreenshot' }, { title: 'Ticket page', description: 'Show the supporter ticket or joining experience.', imageKey: 'ticketingScreenshot' }, { title: 'Gameplay', description: 'Use this slot for live quiz gameplay.', imageKey: 'quizGameplayScreenshot' }, { title: 'Report', description: 'Show the after-event report.', imageKey: 'reportsScreenshot' } ],
    faqs: [ { question: 'Is the quiz product the most mature part of FundRaisely?', answer: 'Yes. The quiz pages should carry the strongest copy and screenshots because this is the first key fundraising game.' }, { question: 'Can quiz fundraisers work for clubs and schools?', answer: 'Yes. Quiz nights are familiar, easy to explain and suitable for sports clubs, PTAs, charities and community groups.' }, { question: 'Can I add real screenshots later?', answer: 'Yes. The template includes named screenshot slots for setup, ticketing, gameplay and reporting.' } ], relatedLinks: [ { label: 'Event formats', to: '/event-formats' }, { label: 'Ticketing', to: '/features/ticketing' }, { label: 'Reports', to: '/features/reports' } ],
  },
  elimination: game('elimination', '/event-formats/elimination', 'Elimination fundraising games for supporter campaigns', 'A last-person-standing style digital fundraiser that can support longer selling windows and one clear winner.', 'rolling_out', 'communityCelebration'),
  'puzzle-challenges': game('puzzle-challenges', '/event-formats/puzzle-challenges', 'Puzzle challenges for event formats', 'A digital challenge format for supporters who enjoy puzzles, problem-solving and prize-led campaigns.', 'rolling_out', 'prizeTable'),
  'escape-room': game('escape-room', '/event-formats/escape-room', 'Escape room fundraisers for community groups', 'A planned digital escape-room style fundraiser for teams, schools and community supporters.', 'coming_soon', 'schoolFundraisingEvent'),
  'treasure-hunt': game('treasure-hunt', '/event-formats/treasure-hunt', 'Treasure hunt fundraisers for local campaigns', 'A planned challenge format for community events, trails and supporter campaigns.', 'coming_soon', 'sportsClubFundraiser'),
};

function game(slug: string, path: string, h1: string, intro: string, status: TemplateContent['status'], imageKey: TemplateContent['imageKey']): TemplateContent {
  const live = status === 'live';
  return { path, seoTitle: h1, seoDescription: intro, eyebrow: 'Event format', h1, intro, visualEmphasis: status === 'coming_soon' ? 'photo_heavy' : 'video_heavy', videoSlot: status === 'rolling_out' ? { title: 'Prepare a gameplay preview for this page', text: 'As this game rolls out, use a short video or animated walkthrough to explain the supporter experience without making the page feel unfinished.', imageKey: 'quizGameplayScreenshot', videoLabel: 'Game preview placeholder', transcript: 'Show what supporters do, how entries work, where prizes fit and what the organiser reviews afterwards.' } : undefined, primaryCta: { label: live ? 'Book a demo' : 'Join the rollout list',to: '/contact' }, secondaryCta: { label: 'Explore all event formats', to: '/event-formats' }, imageKey, status, statusLabel: status === 'rolling_out' ? 'Rolling out soon' : 'Coming soon',
    problemTitle: 'Supporter campaigns need a clear reason to take part', problemText: 'Event formats can give supporters a simple, shareable activity while helping organisers raise funds over a focused campaign window.', solutionTitle: 'A structured game page ready for rollout', solutionText: 'This template explains the supporter experience, how the game raises funds, what hosts need to do and where screenshots will go once the game is ready.',
    benefits: [ { title: 'Supporter experience', text: 'Explain what players will do and why it is fun to join.' }, { title: 'Fundraising model', text: 'Show where tickets, entries, extras or prizes fit.' }, { title: 'Host involvement', text: 'Make the organiser workload clear and manageable.' }, { title: 'Rollout clarity', text: 'Avoid pretending a future game is fully live.' } ],
    process: [ { title: 'Plan the campaign', text: 'Choose the audience, dates, entry route and prize structure.' }, { title: 'Sell entries', text: 'Give supporters a simple way to join before the event or challenge.' }, { title: 'Run the game', text: 'Use the digital format to create a focused fundraising moment.' }, { title: 'Report results', text: 'Review participation, payment status and prize outcomes.' } ],
    screenshotSlots: [ { title: 'Player experience', description: 'Use a gameplay screenshot when available.', imageKey: 'quizGameplayScreenshot' }, { title: 'Host setup', description: 'Show how the organiser configures the fundraiser.', imageKey: 'dashboardScreenshot' }, { title: 'Ticketing', description: 'Show the supporter joining or ticketing journey.', imageKey: 'ticketingScreenshot' } ],
    faqs: [ { question: 'Is this game live today?', answer: status === 'rolling_out' ? 'It is being rolled out soon. The page is structured so final screenshots and copy can be plugged in as the product matures.' : 'Not yet. This page is intentionally marked as coming soon while the platform expands.' }, { question: 'What can organisers use today?', answer: 'Start with quiz fundraisers, ticketing, payment tracking and reports.' }, { question: 'Can this page use gameplay screenshots later?', answer: 'Yes. The template includes clear slots for player, host, ticketing and report visuals.' } ], relatedLinks: relatedGames };
}
