import type { TemplateContent } from './types';

export const quizPages: Record<string, TemplateContent> = {
  index: {
    path: '/quiz', seoTitle: 'Fundraising Quiz Platform', seoDescription: 'Run quiz fundraisers with setup, ticketing, player records, payment tracking and reports.', eyebrow: 'Quiz fundraising', h1: 'Run quiz fundraisers with less admin', intro: 'FundRaisely helps organisers turn a familiar quiz night into a structured fundraising event with clearer ticketing, payment tracking and after-event reports.', primaryCta: { label: 'Book a demo',to: '/contact' }, secondaryCta: { label: 'See how it works', to: '/quiz/how-it-works' }, imageKey: 'communityQuizNight', status: 'live', visualEmphasis: 'video_heavy',
    videoSlot: { title: 'Show the quiz fundraiser from start to finish', text: 'This is the best place for a polished video demo because the quiz is the most mature product. Use it to show setup, ticketing, player experience and reporting.', imageKey: 'quizGameplayScreenshot', videoLabel: 'Fundraising quiz overview video placeholder', transcript: 'Show the organiser creating a quiz, sharing the ticket link, running the quiz, checking payments and reviewing the final report.' }, statusLabel: 'Available first',
    problemTitle: 'Quiz nights are popular, but organisers still carry the admin', problemText: 'A good quiz fundraiser needs promotion, tickets, player lists, payment checking, prizes and reporting. That can become a lot for a small committee.', solutionTitle: 'A structured quiz fundraiser from setup to report', solutionText: 'FundRaisely gives the quiz fundraiser a clearer journey so organisers can focus on the event rather than chasing information.',
    benefits: [ { title: 'Setup flow', text: 'Create the fundraiser, set entry details and prepare the event.' }, { title: 'Ticketing', text: 'Give supporters a clear way to join and register.' }, { title: 'Payment tracking', text: 'Keep expected, claimed and confirmed payments easier to review.' }, { title: 'Reports', text: 'Review totals, winners, prizes and records after the event.' } ],
    process: [ { title: 'Create the quiz', text: 'Set the event details, pricing, prizes and organiser notes.' }, { title: 'Share with supporters', text: 'Use a link to promote the fundraiser and collect details.' }, { title: 'Host the game', text: 'Run the quiz with the right players and event information in place.' }, { title: 'Review the outcome', text: 'Use the report structure for committee review and follow-up.' } ],
    screenshotSlots: [ { title: 'Quiz setup wizard', description: 'Replace with setup flow screenshots.', imageKey: 'dashboardScreenshot' }, { title: 'Ticket page', description: 'Show the supporter registration or ticketing experience.', imageKey: 'ticketingScreenshot' }, { title: 'Live gameplay', description: 'Add real quiz gameplay screenshots here.', imageKey: 'quizGameplayScreenshot' }, { title: 'After-event report', description: 'Show report and reconciliation screens.', imageKey: 'reportsScreenshot' } ],
    faqs: [ { question: 'Can FundRaisely support a local quiz night?', answer: 'Yes. The quiz is the strongest current FundRaisely game format and is suitable for clubs, schools, charities and community groups.' }, { question: 'Can the quiz be remote or in person?', answer: 'The page is structured to explain both in-person and remote/hybrid use cases once final copy is added.' }, { question: 'What screenshots should go on this page?', answer: 'Use the setup wizard, ticket page, host controls, player screen and final report.' } ], relatedLinks: [ { label: 'Quiz demo', to: '/quiz/demo' }, { label: 'Quiz features', to: '/quiz/features' }, { label: 'Quiz how it works', to: '/quiz/how-it-works' } ],
  },
  demo: quizSub('/quiz/demo', 'Book a fundraising quiz demo', 'See the quiz setup, ticket journey, payment tracking and report structure in context.', 'Quiz demo'),
  features: quizSub('/quiz/features', 'Fundraising quiz features', 'Explore the setup, ticketing, player management, payment tracking and reports designed for quiz fundraisers.', 'Quiz features'),
  'how-it-works': quizSub('/quiz/how-it-works', 'How a FundRaisely quiz works', 'A practical step-by-step guide to setting up, sharing, running and reviewing a quiz fundraiser.', 'How it works'),
};

function quizSub(path: string, h1: string, intro: string, eyebrow: string): TemplateContent {
  const isHow = path.endsWith('/how-it-works');
  const isDemo = path.endsWith('/demo');
  return { path, seoTitle: h1, seoDescription: intro, eyebrow, h1, intro, visualEmphasis: isHow || isDemo ? 'video_heavy' : 'screenshot_heavy', videoSlot: isHow || isDemo ? { title: isDemo ? 'What visitors will see in the demo' : 'A step-by-step quiz walkthrough', text: isDemo ? 'Use this page for a short demo teaser video that sets expectations before someone books a call.' : 'A video works well here because the page is explaining a process, not just listing features.', imageKey: 'quizGameplayScreenshot', videoLabel: isDemo ? 'Demo teaser placeholder' : 'How the quiz works video placeholder', transcript: isDemo ? 'Show the setup flow, ticket page, player screen, host view and report so visitors know what will be covered on a demo.' : 'Show each step: create the quiz, share the link, collect entries, run the game and review the report.' } : undefined, primaryCta: { label: 'Book a demo',to: '/contact' }, secondaryCta: { label: 'Quiz overview', to: '/quiz' }, imageKey: 'quizGameplayScreenshot', status: 'live', statusLabel: 'Available first',
    problemTitle: 'Organisers need practical details before they commit', problemText: 'Quiz hosts and committees want to know what the setup involves, what supporters see and what reporting looks like afterwards.', solutionTitle: 'A deeper quiz page ready for product copy', solutionText: 'Use this template to add final quiz copy, screenshots, workflow details and FAQs without changing the route structure.',
    benefits: [ { title: 'Setup', text: 'Show how organisers create the quiz fundraiser.' }, { title: 'Supporter journey', text: 'Explain ticketing, joining and event reminders.' }, { title: 'Host flow', text: 'Show what the host controls during the quiz.' }, { title: 'After-event review', text: 'Explain reports, payment tracking and prize records.' } ],
    process: [ { title: 'Prepare', text: 'Create the quiz fundraiser and add the practical event details.' }, { title: 'Promote', text: 'Share the link with supporters and collect entries.' }, { title: 'Play', text: 'Run the quiz and keep the event structured.' }, { title: 'Report', text: 'Review participation, payments, prizes and totals.' } ],
    screenshotSlots: [ { title: 'Setup screenshot', description: 'Add the setup wizard or admin screen.', imageKey: 'dashboardScreenshot' }, { title: 'Player screenshot', description: 'Add the player or supporter journey.', imageKey: 'quizGameplayScreenshot' }, { title: 'Report screenshot', description: 'Add final report screenshots.', imageKey: 'reportsScreenshot' } ],
    faqs: [ { question: 'Is this final copy?', answer: 'No. It is a structured template with useful holding copy so final copy can be plugged in.' }, { question: 'Should this page have screenshots?', answer: 'Yes. Quiz pages should be screenshot-heavy because this is the most mature product area.' }, { question: 'Should this link to use cases?', answer: 'Yes. Add sports club, schools and charity links from the related section.' } ],
    relatedLinks: [ { label: 'Sports clubs', to: '/use-cases/sports-clubs' }, { label: 'Schools & PTAs', to: '/use-cases/schools-ptas' }, { label: 'Reports', to: '/features/reports' } ] };
}
