import { useEffect, useState } from 'react';
import { Heart, Users, TrendingUp, EyeOff, Wallet, AlertCircle } from 'lucide-react';
import sponsoredActivityMgmtService, { type SponsoredContributionSummary } from '../../../services/SponsoredActivityMgmtService';
import { useCurrency } from '../../../hooks/useCurrency';
export default function ImpactTabSponsoredActivity({ roomId, config }: { roomId: string; config?: any }) {
  const [summary,setSummary]=useState<SponsoredContributionSummary|null>(null);const [error,setError]=useState<string|null>(null);const {fmt}=useCurrency(config);
  useEffect(()=>{sponsoredActivityMgmtService.getSummary(roomId).then(r=>setSummary(r.summary)).catch(e=>setError(e?.message||'Failed to load impact'));},[roomId]);
  if(error)return <div className="p-5"><div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</div></div>;
  return <div className="space-y-5 p-5"><div className="rounded-2xl border p-5" style={{borderColor:'rgba(21,127,133,.25)',background:'rgba(21,127,133,.05)'}}><div className="flex items-center gap-2"><Heart className="h-5 w-5 text-[#157f85]"/><h3 className="font-bold text-[#102532]">Sponsorship impact</h3></div><p className="mt-2 text-sm text-[#52636f]">A live summary of confirmed support for this activity.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[[Heart,'Raised',summary?fmt(summary.confirmedTotal):'-'],[Users,'Confirmed sponsors',summary?.confirmedCount??'-'],[TrendingUp,'Average contribution',summary?fmt(summary.averageConfirmed):'-'],[EyeOff,'Anonymous',summary?.anonymousCount??'-']].map(([Icon,label,value]:any)=><div key={label} className="rounded-xl border border-[#dce1df] bg-white p-4"><Icon className="h-5 w-5 text-[#157f85]"/><p className="mt-2 text-xs font-semibold uppercase text-[#52636f]">{label}</p><p className="mt-1 text-xl font-black text-[#102532]">{value}</p></div>)}</div><div className="rounded-xl border border-[#dce1df] bg-white p-4"><div className="mb-3 flex items-center gap-2"><Wallet className="h-4 w-4 text-[#157f85]"/><h4 className="text-sm font-bold text-[#102532]">Confirmed by payment method</h4></div>{summary?.byMethod?.length?<div className="space-y-2">{summary.byMethod.map(m=><div key={`${m.category}-${m.label}`} className="flex items-center justify-between rounded-lg bg-[#fbf8f2] px-3 py-2 text-sm"><div><p className="font-semibold text-[#102532]">{m.label}</p><p className="text-xs text-[#52636f]">{m.count} contribution{m.count===1?'':'s'}</p></div><p className="font-bold text-[#102532]">{fmt(m.total)}</p></div>)}</div>:<p className="text-sm text-[#52636f]">No confirmed contributions yet.</p>}</div></div>;
}
