import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock, Plus, RefreshCw, Search, ShieldAlert, X } from 'lucide-react';
import sponsoredActivityMgmtService, { type SponsoredContribution } from '../../../services/SponsoredActivityMgmtService';
import { quizPaymentMethodsService, type PaymentMethod } from '../../../services/QuizPaymentMethodsService';
import { useCurrency } from '../../../hooks/useCurrency';

type Filter = 'all' | 'claimed' | 'confirmed' | 'disputed';
function statusPill(status: string) {
  if (status === 'confirmed') return 'border-green-200 bg-green-50 text-green-800';
  if (status === 'disputed') return 'border-rose-200 bg-rose-50 text-rose-800';
  return 'border-amber-200 bg-amber-50 text-amber-800';
}
export default function SponsoredContributionsTab({ roomId, config, roomStatus }: { roomId: string; config?: any; roomStatus: string }) {
  const [rows,setRows]=useState<SponsoredContribution[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [filter,setFilter]=useState<Filter>('all'); const [search,setSearch]=useState(''); const [showAdd,setShowAdd]=useState(false); const [methods,setMethods]=useState<PaymentMethod[]>([]); const [busy,setBusy]=useState<string|null>(null); const {fmt}=useCurrency(config);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await sponsoredActivityMgmtService.listContributions(roomId,{status:filter,search});setRows(r.contributions);}catch(e:any){setError(e?.message||'Failed to load contributions');}finally{setLoading(false);}},[roomId,filter,search]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{quizPaymentMethodsService.getQuizPaymentMethods(roomId).then(r=>setMethods(r.available_methods.filter(m=>r.onnight_method_ids.includes(Number(m.id)) && m.is_enabled))).catch(()=>setMethods([]));},[roomId]);
  const manualMethods=useMemo(()=>methods.filter(m=>!['stripe','crypto'].includes(m.method_category)),[methods]);
  const confirm=async(id:string)=>{setBusy(id);try{await sponsoredActivityMgmtService.confirmContribution(roomId,id);await load();}catch(e:any){setError(e?.message||'Confirmation failed');}finally{setBusy(null);}};
  const dispute=async(id:string)=>{const reason=window.prompt('Why can this payment not be verified?'); if(!reason?.trim()) return; setBusy(id);try{await sponsoredActivityMgmtService.disputeContribution(roomId,id,reason.trim());await load();}catch(e:any){setError(e?.message||'Dispute failed');}finally{setBusy(null);}};
  const writeOff=async(id:string)=>{const row=rows.find(r=>r.id===id);const warning=`Write off ${row?fmt(row.amount):'this contribution'}?\n\nThis means the payment was not received. It will be removed from outstanding/disputed totals, but the contribution and ledger records will remain in the audit trail. This cannot be undone from this screen.`;if(!window.confirm(warning))return;const reason=window.prompt('Why is this contribution being written off?','Payment could not be found');if(!reason?.trim())return;setBusy(id);try{await sponsoredActivityMgmtService.writeOffContribution(roomId,id,reason.trim());await load();}catch(e:any){setError(e?.message||'Write-off failed');}finally{setBusy(null);}};
  return <div className="space-y-4 p-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-[#102532]">Contributions and payments</h3><p className="text-xs text-[#52636f]">Confirm manually verified payments. Stripe and crypto remain webhook/on-chain controlled.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-lg border border-[#dce1df] p-2 text-[#52636f]"><RefreshCw className="h-4 w-4"/></button><button disabled={roomStatus!=='open'} onClick={()=>setShowAdd(true)} className="inline-flex items-center gap-1.5 rounded-lg bg-[#157f85] px-3 py-2 text-xs font-semibold text-white disabled:opacity-40"><Plus className="h-4 w-4"/>Add manual contribution</button></div></div>
    {error&&<div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><AlertCircle className="h-4 w-4"/>{error}</div>}
    <div className="flex flex-wrap gap-2">{(['all','claimed','confirmed','disputed'] as Filter[]).map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${filter===f?'bg-[#157f85] text-white':'border border-[#dce1df] bg-white text-[#52636f]'}`}>{f==='claimed'?'Awaiting':f[0].toUpperCase()+f.slice(1)}</button>)}<div className="relative ml-auto"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#8a9bab]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search sponsor or reference" className="rounded-lg border border-[#dce1df] py-2 pl-9 pr-3 text-xs"/></div></div>
    {loading?<div className="p-10 text-center text-sm text-[#52636f]">Loading contributions…</div>:rows.length===0?<div className="rounded-xl border border-dashed border-[#dce1df] p-10 text-center text-sm text-[#52636f]">No matching contributions yet.</div>:<div className="overflow-hidden rounded-xl border border-[#dce1df] bg-white">{rows.map(r=>{const auto=['stripe','crypto'].includes(r.paymentMethodCategory);return <div key={r.id} className="border-b border-[#f1f0ee] p-4 last:border-0"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><p className="font-semibold text-[#102532]">{r.isAnonymous?'Anonymous':r.displayName||r.sponsorName||'Sponsor'}</p><span className={`rounded-full border px-2 py-0.5 text-[10px] font-bold ${statusPill(r.status)}`}>{r.status==='claimed'?'Awaiting confirmation':r.status}</span></div><p className="mt-1 text-xs text-[#52636f]">{r.paymentMethodLabel||r.paymentMethodCategory}{r.paymentReference?` · Ref: ${r.paymentReference}`:''}</p>{r.message&&<p className="mt-2 text-sm italic text-[#52636f]">“{r.message}”</p>}{r.disputeReason&&<p className="mt-2 text-xs text-rose-700">Dispute: {r.disputeReason}</p>}</div><div className="text-right"><p className="text-lg font-black text-[#102532]">{fmt(r.amount)}</p><p className="text-[10px] text-[#8a9bab]">{r.createdAt?new Date(r.createdAt).toLocaleString('en-IE'):'—'}</p></div></div>{r.status==='claimed'&&<div className="mt-3 flex justify-end gap-2">{auto?<span className="inline-flex items-center gap-1 rounded-lg bg-[#f6f1e8] px-3 py-1.5 text-xs text-[#52636f]"><ShieldAlert className="h-3.5 w-3.5"/>Auto verification required</span>:<button disabled={busy===r.id} onClick={()=>void confirm(r.id)} className="inline-flex items-center gap-1 rounded-lg bg-green-600 px-3 py-1.5 text-xs font-semibold text-white"><CheckCircle2 className="h-3.5 w-3.5"/>Confirm paid</button>}<button disabled={busy===r.id} onClick={()=>void dispute(r.id)} className="rounded-lg border border-rose-200 px-3 py-1.5 text-xs font-semibold text-rose-700">Dispute</button></div>}{r.status==='disputed'&&!auto&&<div className="mt-3 flex justify-end gap-2"><button disabled={busy===r.id} onClick={()=>void writeOff(r.id)} className="rounded-lg border border-rose-300 bg-white px-3 py-1.5 text-xs font-semibold text-rose-700">Write off</button><button disabled={busy===r.id} onClick={()=>void confirm(r.id)} className="inline-flex items-center gap-1 rounded-lg bg-green-600 px-3 py-1.5 text-xs font-semibold text-white"><CheckCircle2 className="h-3.5 w-3.5"/>Confirm after review</button></div>}</div>})}</div>}
    {showAdd&&<AddContributionModal roomId={roomId} methods={manualMethods} currency={config?.currency||'EUR'} onClose={()=>setShowAdd(false)} onSaved={async()=>{setShowAdd(false);await load();}}/>}
  </div>;
}
function AddContributionModal({roomId,methods,currency,onClose,onSaved}:{roomId:string;methods:PaymentMethod[];currency:string;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState('');const [email,setEmail]=useState('');const [amount,setAmount]=useState('');const [method,setMethod]=useState(methods[0]?.id?String(methods[0].id):'');const [reference,setReference]=useState('');const [message,setMessage]=useState('');const [anonymous,setAnonymous]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<string|null>(null);
  const save=async()=>{setSaving(true);setError(null);try{await sponsoredActivityMgmtService.addManualContribution(roomId,{sponsorName:name,sponsorEmail:email||null,displayName:anonymous?'Anonymous':name,isAnonymous:anonymous,message:message||null,amount:Number(amount),currency,clubPaymentMethodId:Number(method),paymentReference:reference||null});await onSaved();}catch(e:any){setError(e?.message||'Could not add contribution');}finally{setSaving(false);}};
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-bold text-[#102532]">Add manual contribution</h3><p className="text-xs text-[#52636f]">Creates an awaiting-confirmation contribution and ledger record.</p></div><button onClick={onClose}><X className="h-5 w-5"/></button></div><div className="grid gap-3 p-5 sm:grid-cols-2">{error&&<div className="sm:col-span-2 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<label className="text-xs text-[#52636f]">Sponsor name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label><label className="text-xs text-[#52636f]">Email (optional)<input value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label><label className="text-xs text-[#52636f]">Amount<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label><label className="text-xs text-[#52636f]">Payment method<select value={method} onChange={e=>setMethod(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">Select</option>{methods.map(m=><option key={m.id} value={m.id}>{m.method_label}</option>)}</select></label><label className="text-xs text-[#52636f] sm:col-span-2">Payment reference<input value={reference} onChange={e=>setReference(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label><label className="text-xs text-[#52636f] sm:col-span-2">Message<textarea value={message} onChange={e=>setMessage(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-sm" rows={2}/></label><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/>Show as anonymous</label></div><div className="flex justify-end gap-2 border-t bg-[#fbf8f2] p-4"><button onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancel</button><button disabled={saving||!name.trim()||!method||Number(amount)<=0} onClick={()=>void save()} className="rounded-lg bg-[#157f85] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{saving?'Saving…':'Add contribution'}</button></div></div></div>;
}
