name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop, main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      # typecheck: non-blocking for now (remove "|| true" later)
      - run: npx tsc --noEmit || true
      # Required step — if this fails, PRs can't merge
      - run: npm run build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true   # results visible but won't block merges
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

